version: "3.8"

volumes:
  localnet-volume:

services:
  subtensor-localnet:
    container_name: subtensor-localnet
    volumes:
      - localnet-volume:/tmp/blockchain
    image: hamzatrq/subtensor-localnet:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: subtensor
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    ports:
      - "30333:30333"
      - "30334:30334"
      - "30335:30335"
      - "9933:9933"
      - "9934:9934"
      - "9935:9935"
      - "9944:9944"
      - "9946:9946"
      - "9947:9947"
    expose:
      - "30333"
      - "30334"
      - "30335"
      - "9933"
      - "9934"
      - "9935"
      - "9944"
      - "9946"
      - "9947"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    command:
      - /bin/bash
      - -c
      - |
        /subtensor/scripts/localnet.sh
